from __future__ import annotations


# Add new dropdown options here.
# The editor combines these values with values already present in core.student_meta.
# For brand-new students, add at least the following when needed:
# - student_id
# - display_name
# - template_name
# - group
# - variant
# - growth_material_main / growth_material_sub

FIELD_OPTIONS: dict[str, tuple[str, ...]] = {
    "student_id": (),
    "display_name": (),
    "template_name": (),
    "group": (),
    "variant": (),
    "school": (
        "Abydos",
        "Gehenna",
        "Trinity",
        "Millennium",
        "Hyakkiyako",
        "Shanhaijing",
        "Red Winter",
        "Valkyrie",
        "Arius",
        "SRT",
        "Wild Hunt",
        "Highlander",
        "Tokiwadai",
        "Sakugawa",
        "ETC",
    ),
    "rarity": (
        "1",
        "2",
        "3",
    ),
    "recruit_type": (
        "Regular",
        "Limited",
        "Festival",
        "Event",
    ),
    "attack_type": (
        "Explosive",
        "Piercing",
        "Mystic",
        "Sonic",
        "Chemical",
    ),
    "attack_type_trait": (),
    "defense_type": (
        "Light",
        "Heavy",
        "Special",
        "Elastic",
        "Composite",
    ),
    "growth_material_main": (
        "Nebra Disk",
        "Phaistos Disc",
        "Wolfsegg Steel",
        "Nimrud Lens",
        "Madrake Extract",
        "Rohonc Codex",
        "Aether Essence",
        "Antikythera Mechanism",
        "Voynich Manuscript",
        "Crystal Haniwa",
        "Totem Pole",
        "Ancient Battery",
        "Golden Fleece",
        "Okiku Doll",
        "Disco Colgante",
        "Atlantis Medal",
        "Roman Dodecahedron",
        "Quimbaya Relic",
        "Istanbul Rocket",
        "Mystery Stone",
    ),
    "growth_material_sub": (),
    "equipment_slot_1": (
        "Gloves",
        "Hat",
        "Shoes"
    ),
    "equipment_slot_2": (
        "Badge",
        "Bag",
        "Hairpin",
    ),
    "equipment_slot_3": (
        "Charm",
        "Necklace",
        "Watch",
    ),
    "combat_class": (
        "striker",
        "special",
    ),
    "cover_type": (
        "cover",
        "no_cover",
    ),
    "range_type": (
        "350",
        "450",
        "550",
        "650",
        "750",
        "850",
        "1000",
    ),
    "role": (
        "tanker",
        "dealer",
        "healer",
        "supporter",
        "t_s",
    ),
    "weapon_type": (
        "AR",
        "SR",
        "HG",
        "SMG",
        "MG",
        "SG",
        "RL",
        "GL",
        "MT",
        "RG",
        "FT",
    ),
    "position": (
        "front",
        "middle",
        "back",
    ),
    "terrain_outdoor": (
        "SS",
        "S",
        "A",
        "B",
        "C",
        "D",
    ),
    "terrain_urban": (
        "SS",
        "S",
        "A",
        "B",
        "C",
        "D",
    ),
    "terrain_indoor": (
        "SS",
        "S",
        "A",
        "B",
        "C",
        "D",
    ),
    "weapon3_terrain_boost": (
        "terrain_outdoor",
        "terrain_urban",
        "terrain_indoor",
    ),
    "has_favorite_item": (
        "yes",
        "no",
    ),
    "farmable": (
        "yes",
        "no",
    ),
    "passive_stat": (
        "AccuracyPoint",
        "AttackPower",
        "AttackSpeed",
        "CriticalDamageRate",
        "CriticalPoint",
        "DefensePower",
        "DodgePoint",
        "HealEffectivenessRate",
        "HealPower",
        "MaxHP",
        "MoveSpeed",
        "OppressionPower",
        "Range",
    ),
    "weapon_passive_stat": (
        "AccuracyPoint",
        "AmmoCount",
        "AttackPower",
        "AttackSpeed",
        "BlockRate",
        "CriticalDamageRate",
        "CriticalPoint",
        "DefensePenetration",
        "DefensePower",
        "DodgePoint",
        "EnhanceExplosionRate",
        "EnhanceMysticRate",
        "EnhancePierceRate",
        "EnhanceSonicRate",
        "ExtendBuffDuration",
        "ExtendDebuffDuration",
        "HealEffectivenessRate",
        "HealPower",
        "MaxHP",
        "OppressionPower",
        "StabilityPoint",
    ),
    "extra_passive_stat": (
        "AccuracyPoint",
        "AttackPower",
        "AttackSpeed",
        "CriticalChanceResistPoint",
        "CriticalDamageRate",
        "CriticalDamageResistRate",
        "CriticalPoint",
        "DamageRatio2",
        "DamagedRatio2",
        "DefensePower",
        "DodgePoint",
        "EnhanceExDamageRate",
        "EnhanceExplosionRate",
        "EnhanceMysticRate",
        "EnhancePierceRate",
        "EnhanceSonicRate",
        "HealEffectivenessRate",
        "HealPower",
        "IgnoreDelayCount",
        "MaxHP",
        "OppressionPower",
        "OppressionResist",
        "Range",
        "RegenCost",
    ),
    "skill_buff": (
        "AccuracyPoint",
        "AttackPower",
        "AttackSpeed",
        "CostChange",
        "CriticalChanceResistPoint",
        "CriticalDamageRate",
        "CriticalDamageResistRate",
        "CriticalPoint",
        "DefensePower",
        "DodgePoint",
        "DotHeal",
        "EnhanceBasicsDamageRate",
        "EnhanceExDamageRate",
        "EnhanceExplosionRate",
        "EnhanceMysticRate",
        "EnhancePierceRate",
        "EnhanceSonicRate",
        "HealEffectivenessRate",
        "HealPower",
        "MaxHP",
        "MoveSpeed",
        "OppressionPower",
        "OppressionResist",
        "Range",
        "RegenCost",
        "Shield",
    ),
    "skill_debuff": (
        "AccuracyPoint",
        "AttackPower",
        "AttackSpeed",
        "Burn",
        "Cheerleading",
        "Chill",
        "ChillDamagedIncrease",
        "ConcentratedTarget",
        "CriticalChanceResistPoint",
        "CriticalDamageRate",
        "CriticalDamageResistRate",
        "CriticalPoint",
        "DamageByHit_Damaged",
        "DefensePower",
        "DodgePoint",
        "ElectricShock",
        "HealEffectivenessRate",
        "MoveSpeed",
        "OppressionResist",
        "Poison",
        "ReduceWeakDamagedRate",
    ),
    "skill_cc": (
        "Confusion",
        "Fear",
        "Provoke",
        "Stunned",
    ),
    "skill_special": (
        "Accumulation",
        "AmplifyDoTAdditionalTick_Poison",
        "AmplifyDoTReducePeriod_Chill",
        "CH0187Mod",
        "CH0224_Public",
        "CH0239_ExtraPassive",
        "CH0280_Ex_01",
        "CH0309_Ex",
        "FormChange",
        "Fury",
        "SilverBullet",
    ),
    "skill_heal_targets": (
        "Self",
        "Ally",
        "Any",
    ),
    "skill_dispel_targets": (
        "Self",
        "Ally",
        "Any",
    ),
    "skill_reposition_targets": (
        "Self",
        "Ally",
        "Enemy",
    ),
    "skill_summon_types": (),
    "skill_ignore_cover": (
        "yes",
        "no",
    ),
    "skill_is_area_damage": (
        "yes",
        "no",
    ),
    "skill_buff_specials": (
        "AccuracyPoint",
        "AttackPower",
        "AttackSpeed",
        "CriticalChanceResistPoint",
        "CriticalDamageRate",
        "CriticalDamageResistRate",
        "CriticalPoint",
        "DefensePower",
        "DodgePoint",
        "EnhanceExplosionRate",
        "EnhanceMysticRate",
        "EnhancePierceRate",
        "HealEffectivenessRate",
        "HealPower",
        "MaxHP",
        "OppressionPower",
        "OppressionResist",
        "RegenCost",
    ),
    "skill_knockback": (
        "yes",
        "no",
    ),
}
